Salief/clean up curation logic interface
public-assembly/AssemblyPress pull request #77
Opened 2023-05-06 21:21 UTC by salieflewis

2023-05-06 21:24 UTC, salieflewis commented
https://www.loom.com/share/2abc52ff8c974d4c8f162d333a800ec4

2023-05-07 14:01 UTC, 0xTranqui requested changes
this looks great! there is a tad bit of inconsitency on the Config struct in relation to the Listing struct -- the first two slots dont use the word "bytes" in them like we use for that third slot or for the Listing struct. im happy with the general formatting, and would also suggest/ask you to throw in whatever prettier config file you used to generate this into the entire repo itself!

2023-05-07 14:21 UTC, salieflewis commented
I was conscious of that, but not sure if the approach I just used is redundant. Let me know what you think, and also I think adding the prettier config should be a separate PR.

2023-05-07 14:22 UTC, 0xTranqui approved these changes

2023-05-07 14:22 UTC, merged